# Autogenerated by devscripts/update-version.py

__version__ = '2026.01.02.192300'

RELEASE_GIT_HEAD = '211246651746e2886eced7eec69dab84b7bd958c'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'flower-elf/yt-dlp'

ORIGIN = 'flower-elf/yt-dlp'

_pkg_version = '2026.01.02.192300'
