# Autogenerated by devscripts/update-version.py

__version__ = '2025.04.25.005709'

RELEASE_GIT_HEAD = 'ced38528f6ed4b72d407b98810bff5cf49602b5f'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'flower-elf/yt-dlp'

_pkg_version = '2025.04.25.005709'
