# Autogenerated by devscripts/update-version.py

__version__ = '2025.09.06.220327'

RELEASE_GIT_HEAD = '8a2f93d8499e496b9466d2d346cf4ffc26b6d36b'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'flower-elf/yt-dlp'

ORIGIN = 'flower-elf/yt-dlp'

_pkg_version = '2025.09.06.220327'
